version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: atlasstore-postgres
    restart: always
    environment:
      POSTGRES_USER: atlasstore
      POSTGRES_PASSWORD: atlaspassword
      POSTGRES_DB: atlasstore
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
