// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: pkg/pb/storage.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StorageNode_SaveChunk_FullMethodName   = "/pb.StorageNode/SaveChunk"
	StorageNode_GetChunk_FullMethodName    = "/pb.StorageNode/GetChunk"
	StorageNode_DeleteChunk_FullMethodName = "/pb.StorageNode/DeleteChunk"
	StorageNode_Health_FullMethodName      = "/pb.StorageNode/Health"
)

// StorageNodeClient is the client API for StorageNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageNodeClient interface {
	// 4 main internal api
	SaveChunk(ctx context.Context, in *SaveChunkRequest, opts ...grpc.CallOption) (*SaveChunkResponse, error)
	GetChunk(ctx context.Context, in *GetChunkRequest, opts ...grpc.CallOption) (*GetChunkResponse, error)
	DeleteChunk(ctx context.Context, in *DeleteChunkRequest, opts ...grpc.CallOption) (*DeleteChunkResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type storageNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageNodeClient(cc grpc.ClientConnInterface) StorageNodeClient {
	return &storageNodeClient{cc}
}

func (c *storageNodeClient) SaveChunk(ctx context.Context, in *SaveChunkRequest, opts ...grpc.CallOption) (*SaveChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveChunkResponse)
	err := c.cc.Invoke(ctx, StorageNode_SaveChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageNodeClient) GetChunk(ctx context.Context, in *GetChunkRequest, opts ...grpc.CallOption) (*GetChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChunkResponse)
	err := c.cc.Invoke(ctx, StorageNode_GetChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageNodeClient) DeleteChunk(ctx context.Context, in *DeleteChunkRequest, opts ...grpc.CallOption) (*DeleteChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteChunkResponse)
	err := c.cc.Invoke(ctx, StorageNode_DeleteChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageNodeClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, StorageNode_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageNodeServer is the server API for StorageNode service.
// All implementations must embed UnimplementedStorageNodeServer
// for forward compatibility.
type StorageNodeServer interface {
	// 4 main internal api
	SaveChunk(context.Context, *SaveChunkRequest) (*SaveChunkResponse, error)
	GetChunk(context.Context, *GetChunkRequest) (*GetChunkResponse, error)
	DeleteChunk(context.Context, *DeleteChunkRequest) (*DeleteChunkResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedStorageNodeServer()
}

// UnimplementedStorageNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageNodeServer struct{}

func (UnimplementedStorageNodeServer) SaveChunk(context.Context, *SaveChunkRequest) (*SaveChunkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveChunk not implemented")
}
func (UnimplementedStorageNodeServer) GetChunk(context.Context, *GetChunkRequest) (*GetChunkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChunk not implemented")
}
func (UnimplementedStorageNodeServer) DeleteChunk(context.Context, *DeleteChunkRequest) (*DeleteChunkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteChunk not implemented")
}
func (UnimplementedStorageNodeServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedStorageNodeServer) mustEmbedUnimplementedStorageNodeServer() {}
func (UnimplementedStorageNodeServer) testEmbeddedByValue()                     {}

// UnsafeStorageNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageNodeServer will
// result in compilation errors.
type UnsafeStorageNodeServer interface {
	mustEmbedUnimplementedStorageNodeServer()
}

func RegisterStorageNodeServer(s grpc.ServiceRegistrar, srv StorageNodeServer) {
	// If the following call panics, it indicates UnimplementedStorageNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageNode_ServiceDesc, srv)
}

func _StorageNode_SaveChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageNodeServer).SaveChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageNode_SaveChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageNodeServer).SaveChunk(ctx, req.(*SaveChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageNode_GetChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageNodeServer).GetChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageNode_GetChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageNodeServer).GetChunk(ctx, req.(*GetChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageNode_DeleteChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageNodeServer).DeleteChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageNode_DeleteChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageNodeServer).DeleteChunk(ctx, req.(*DeleteChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageNode_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageNodeServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageNode_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageNodeServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageNode_ServiceDesc is the grpc.ServiceDesc for StorageNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.StorageNode",
	HandlerType: (*StorageNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveChunk",
			Handler:    _StorageNode_SaveChunk_Handler,
		},
		{
			MethodName: "GetChunk",
			Handler:    _StorageNode_GetChunk_Handler,
		},
		{
			MethodName: "DeleteChunk",
			Handler:    _StorageNode_DeleteChunk_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _StorageNode_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/pb/storage.proto",
}
