// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: pkg/pb/storage.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveChunkRequest) Reset() {
	*x = SaveChunkRequest{}
	mi := &file_pkg_pb_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveChunkRequest) ProtoMessage() {}

func (x *SaveChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveChunkRequest.ProtoReflect.Descriptor instead.
func (*SaveChunkRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_storage_proto_rawDescGZIP(), []int{0}
}

func (x *SaveChunkRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *SaveChunkRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SaveChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveChunkResponse) Reset() {
	*x = SaveChunkResponse{}
	mi := &file_pkg_pb_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveChunkResponse) ProtoMessage() {}

func (x *SaveChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveChunkResponse.ProtoReflect.Descriptor instead.
func (*SaveChunkResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_storage_proto_rawDescGZIP(), []int{1}
}

func (x *SaveChunkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkRequest) Reset() {
	*x = GetChunkRequest{}
	mi := &file_pkg_pb_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkRequest) ProtoMessage() {}

func (x *GetChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkRequest.ProtoReflect.Descriptor instead.
func (*GetChunkRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_storage_proto_rawDescGZIP(), []int{2}
}

func (x *GetChunkRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type GetChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // The raw encrypted chunk data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkResponse) Reset() {
	*x = GetChunkResponse{}
	mi := &file_pkg_pb_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkResponse) ProtoMessage() {}

func (x *GetChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkResponse.ProtoReflect.Descriptor instead.
func (*GetChunkResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_storage_proto_rawDescGZIP(), []int{3}
}

func (x *GetChunkResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChunkRequest) Reset() {
	*x = DeleteChunkRequest{}
	mi := &file_pkg_pb_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChunkRequest) ProtoMessage() {}

func (x *DeleteChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChunkRequest.ProtoReflect.Descriptor instead.
func (*DeleteChunkRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_storage_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteChunkRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type DeleteChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChunkResponse) Reset() {
	*x = DeleteChunkResponse{}
	mi := &file_pkg_pb_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChunkResponse) ProtoMessage() {}

func (x *DeleteChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChunkResponse.ProtoReflect.Descriptor instead.
func (*DeleteChunkResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_storage_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteChunkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_pkg_pb_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_storage_proto_rawDescGZIP(), []int{6}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	DataDir       string                 `protobuf:"bytes,2,opt,name=data_dir,json=dataDir,proto3" json:"data_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_pkg_pb_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_storage_proto_rawDescGZIP(), []int{7}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetDataDir() string {
	if x != nil {
		return x.DataDir
	}
	return ""
}

var File_pkg_pb_storage_proto protoreflect.FileDescriptor

const file_pkg_pb_storage_proto_rawDesc = "" +
	"\n" +
	"\x14pkg/pb/storage.proto\x12\x02pb\":\n" +
	"\x10SaveChunkRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"-\n" +
	"\x11SaveChunkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"%\n" +
	"\x0fGetChunkRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"&\n" +
	"\x10GetChunkResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"(\n" +
	"\x12DeleteChunkRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"/\n" +
	"\x13DeleteChunkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x0f\n" +
	"\rHealthRequest\"C\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x19\n" +
	"\bdata_dir\x18\x02 \x01(\tR\adataDir2\xef\x01\n" +
	"\vStorageNode\x128\n" +
	"\tSaveChunk\x12\x14.pb.SaveChunkRequest\x1a\x15.pb.SaveChunkResponse\x125\n" +
	"\bGetChunk\x12\x13.pb.GetChunkRequest\x1a\x14.pb.GetChunkResponse\x12>\n" +
	"\vDeleteChunk\x12\x16.pb.DeleteChunkRequest\x1a\x17.pb.DeleteChunkResponse\x12/\n" +
	"\x06Health\x12\x11.pb.HealthRequest\x1a\x12.pb.HealthResponseB%Z#github.com/farhan/atlasstore/pkg/pbb\x06proto3"

var (
	file_pkg_pb_storage_proto_rawDescOnce sync.Once
	file_pkg_pb_storage_proto_rawDescData []byte
)

func file_pkg_pb_storage_proto_rawDescGZIP() []byte {
	file_pkg_pb_storage_proto_rawDescOnce.Do(func() {
		file_pkg_pb_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_pb_storage_proto_rawDesc), len(file_pkg_pb_storage_proto_rawDesc)))
	})
	return file_pkg_pb_storage_proto_rawDescData
}

var file_pkg_pb_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_pb_storage_proto_goTypes = []any{
	(*SaveChunkRequest)(nil),    // 0: pb.SaveChunkRequest
	(*SaveChunkResponse)(nil),   // 1: pb.SaveChunkResponse
	(*GetChunkRequest)(nil),     // 2: pb.GetChunkRequest
	(*GetChunkResponse)(nil),    // 3: pb.GetChunkResponse
	(*DeleteChunkRequest)(nil),  // 4: pb.DeleteChunkRequest
	(*DeleteChunkResponse)(nil), // 5: pb.DeleteChunkResponse
	(*HealthRequest)(nil),       // 6: pb.HealthRequest
	(*HealthResponse)(nil),      // 7: pb.HealthResponse
}
var file_pkg_pb_storage_proto_depIdxs = []int32{
	0, // 0: pb.StorageNode.SaveChunk:input_type -> pb.SaveChunkRequest
	2, // 1: pb.StorageNode.GetChunk:input_type -> pb.GetChunkRequest
	4, // 2: pb.StorageNode.DeleteChunk:input_type -> pb.DeleteChunkRequest
	6, // 3: pb.StorageNode.Health:input_type -> pb.HealthRequest
	1, // 4: pb.StorageNode.SaveChunk:output_type -> pb.SaveChunkResponse
	3, // 5: pb.StorageNode.GetChunk:output_type -> pb.GetChunkResponse
	5, // 6: pb.StorageNode.DeleteChunk:output_type -> pb.DeleteChunkResponse
	7, // 7: pb.StorageNode.Health:output_type -> pb.HealthResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_pb_storage_proto_init() }
func file_pkg_pb_storage_proto_init() {
	if File_pkg_pb_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_pb_storage_proto_rawDesc), len(file_pkg_pb_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_storage_proto_goTypes,
		DependencyIndexes: file_pkg_pb_storage_proto_depIdxs,
		MessageInfos:      file_pkg_pb_storage_proto_msgTypes,
	}.Build()
	File_pkg_pb_storage_proto = out.File
	file_pkg_pb_storage_proto_goTypes = nil
	file_pkg_pb_storage_proto_depIdxs = nil
}
